# Default workflow configuration

workflow:
  id: "default_workflow"
  description: "Default workflow for processing natural language queries"
  
  # Initial context to be passed to workflow stages
  initial_context:
    db_path: "example.sqlite"
  
  # Workflow stages
  stages:
    - id: "schema_generation"
      component_type: "schema_generators"
      component_id: "sqlite_schema"
      error_policy: "fail"
      config:
        include_system_tables: false
    
    - id: "prompt_generation"
      component_type: "prompt_generators"
      component_id: "simple_prompt"
      error_policy: "fail"
      config:
        template: "Given the following schema:\n\n{schema}\n\nGenerate a SQL query for: {query}"
    
    - id: "query_execution"
      component_type: "query_executors"
      component_id: "sqlite_executor"
      error_policy: "fail"
      config:
        read_only: true
    
    - id: "response_formatting"
      component_type: "response_formatters"
      component_id: "json_formatter"
      error_policy: "continue"
      config:
        include_metadata: true
        pretty_print: true 