# NLP-to-SQL System Configuration

# Application Settings
app:
  name: "NLP-to-SQL System"
  debug: true
  log_level: "debug"  # debug, info, warning, error
  
# Logging Configuration
logging:
  level: "debug"          # debug, info, warning, error, critical
  console_output: true   # Whether to output logs to console
  file_output: true      # Whether to output logs to file
  log_dir: "logs"        # Directory for log files
  file_name_pattern: "app_%Y%m%d.log"  # Log file name pattern with date format
  format: "%(asctime)s [%(levelname)s] %(name)s - %(message)s"  # Log format
  date_format: "%Y-%m-%d %H:%M:%S"     # Date format in logs
  max_file_size_mb: 10   # Max size of log file before rotation (in MB)
  max_files: 5           # Number of rotated log files to keep
  
# Database Settings
database:
  type: "sqlite"  # sqlite, postgres, mysql (future)
  path: "example.sqlite"
  seed_on_startup: true
  seed_script: null  # Path to custom SQL seed script, null for default data
  
  # PostgreSQL connection settings (used when type is "postgres")
  connection_string: "postgresql://username:password@localhost:5432/database"

# LLM Provider Settings
llm:
  provider: "ollama"  # ollama, openai
  
  # OpenAI-specific settings
  openai:
    model: "gpt-3.5-turbo"
    api_key: "${OPENAI_API_KEY}"  # Uses environment variable
    temperature: 0.0
    max_tokens: 500
    
  # Ollama-specific settings
  ollama:
    model: "llama3.2:3b"
    host: "http://localhost:11434"
    temperature: 0.0
    
# Schema Agent Settings
schema_agent:
  cache_enabled: true
  embedding_model: "local"  # local, openai
  embedding_settings:
    use_semantic_matching: true   # Whether to use semantic matching for table relevance
    similarity_threshold: 0.3     # Minimum similarity score for table matches
    max_tables: 5                 # Maximum number of tables to consider relevant
    include_column_matches: true  # Whether to include columns in matching
  
# Prompt Agent Settings
prompt_agent:
  include_relationships: true
  include_examples: true
  
# Query Generator Settings
query_generator:
  max_retries: 3
  validation_enabled: true
  validation_mode: "syntax_only"  # Options: "full", "syntax_only", "none"
  
# Query Executor Settings
query_executor:
  read_only: true  # For security, only allow SELECT queries
  timeout_seconds: 10
  
# UI Settings
ui:
  theme: "light"  # light, dark
  page_title: "NLP to SQL Converter"
  page_icon: "🔍"
  layout: "wide"  # wide, centered 