# Help documentation

# Help target
help:
	@echo "Available commands:"
	@echo "  make setup            : Set up environment and dependencies"
	@echo "  make install          : Install Python dependencies"
	@echo "  make install-test     : Install pytest and test dependencies"
	@echo "  make setup-ollama     : Set up Ollama with Llama 3.2 3B model"
	@echo "  make run-cli          : Run CLI version"
	@echo "  make run-api          : Run API version"
	@echo "  make run-ui           : Run Streamlit UI"
	@echo "  make run-demo         : Run interactive demo script"
	@echo "  make run-demo-config  : Run demo with configuration display"
	@echo "  make test             : Run tests"
	@echo "  make pytest           : Run all pytest-based tests"
	@echo "  make test-api         : Run API tests"
	@echo "  make test-db          : Run database connector tests"
	@echo "  make test-db-integration : Run database integration tests with SQLite"
	@echo "  make test-postgres    : Run database integration tests with PostgreSQL"
	@echo "  make test-all-db      : Run database integration tests with both SQLite and PostgreSQL"
	@echo "  make test-embeddings  : Run tests for embeddings"
	@echo "  make test-nlsql       : Run comprehensive NL-to-SQL tests"
	@echo "  make test-validation-modes : Run SQL validation modes test"
	@echo "  make test-all         : Run ALL test types sequentially"
	@echo "  make run-demo-questions: Run demo questions with expected answers"
	@echo "  make check-ollama     : Check if Ollama is running and start if not"
	@echo "  make env              : Create .env file from template"
	@echo "  make config-openai    : Configure to use OpenAI"
	@echo "  make config-ollama    : Configure to use Ollama"
	@echo "  make clean            : Clean up environment"
	@echo "  make schema-extract   : Extract schema from database"
	@echo "  make schema-enrich    : Enrich schema with descriptions"
	@echo "  make schema-embed     : Generate embeddings for schema"
	@echo "  make schema-docs      : Run full schema documentation workflow"
	@echo "  make schema-pure      : Generate pure database schema with enum values"
	@echo ""
	@echo "Neo4j commands:"
	@echo "  make neo4j-start      : Start Neo4j container"
	@echo "  make neo4j-stop       : Stop Neo4j container"
	@echo "  make neo4j-seed       : Seed Neo4j with test data"
	@echo "  make neo4j-seed-large : Seed Neo4j with large-scale realistic data"
	@echo "  make neo4j-test       : Run Neo4j integration tests"
	@echo "  make neo4j-browser    : Open Neo4j browser UI"
	@echo "  make neo4j-embed-schema : Embed Neo4j schema information"
	@echo "  make neo4j-search     : Run Neo4j document search demo"
	@echo ""
	@echo "  make help             : Show this help message" 